name: black-action

on: [push, pull_request]

jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "./src"
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python"
          commit-message: ":art: Formatting code"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. 
            This pull request fix these issues.
          base: ${{ github.head_ref }}
          branch: actions/black