name: "Formatting code"

on: [push, pull_request]

jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Check files
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "./src"
      - name: Commit changes
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: ":art: Formatting code ${{ github.sha }}"
